version: '3.8'

services:
  hockey-backend:
    image: ghcr.io/josefjura/hockey/backend:latest
    container_name: hockey_server
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hockey-server.rule=Host(`api.hockey.joseforge.cz`)"
      - "traefik.http.routers.hockey-server.entrypoints=websecure"
      - "traefik.http.routers.hockey-server.tls.certresolver=myresolver"
      - "traefik.http.services.hockey-server.loadbalancer.server.port=8080"
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      # Database
      - DATABASE_URL=sqlite:/app/data/hockey.db?mode=rwc

      # JWT Configuration (NEW - Required for OAuth2 auth)
      - HMAC_KEY=7f3a9b2c8d4e1f6a9b2c8d4e1f6a9b2c8d4e1f649b2c8d4e1f6a9b62
      - JWT_PRIVATE_KEY_PATH=/app/keys/jwt_private.pem
      - JWT_PUBLIC_KEY_PATH=/app/keys/jwt_public.pem
      - JWT_ACCESS_TOKEN_DURATION_MINUTES=15
      - JWT_REFRESH_TOKEN_DURATION_DAYS=7

      # Server Configuration
      - ENVIRONMENT=production
      - RUST_LOG=info,jura_hockey=debug

      # CORS Configuration
      - CORS_ORIGINS=https://hockey.joseforge.cz
      - CORS_METHODS=GET,POST,PUT,DELETE,OPTIONS
      - CORS_HEADERS=content-type,authorization
    volumes:
      - /home/beardo/data/hockey:/app/data
      - /home/beardo/keys/hockey:/app/keys:ro  # NEW - Mount RSA keys for JWT
    restart: always

  hockey-frontend:
    image: ghcr.io/josefjura/hockey/frontend:latest
    container_name: hockey_web
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hockey-web.rule=Host(`hockey.joseforge.cz`)"
      - "traefik.http.routers.hockey-web.entrypoints=websecure"
      - "traefik.http.routers.hockey-web.tls.certresolver=myresolver"
      - "traefik.http.services.hockey-web.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.www-redirect.redirectregex.regex=^https?://www\\.(.+)"
      - "traefik.http.middlewares.www-redirect.redirectregex.replacement=https://$${1}"
      - "traefik.http.routers.hockey-web.middlewares=www-redirect"
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      # NextAuth Configuration
      - NEXTAUTH_URL=https://hockey.joseforge.cz
      - NEXTAUTH_URL_INTERNAL=http://hockey_web:3000
      - NEXTAUTH_SECRET=k9m2p5r8s1t4u7v0w3x6y9z2a5b8c1d4e7f0g3h6i9j2k5l8m1n4o7p0
      - AUTH_TRUST_HOST=true
      
      # Backend Connection
      - HOCKEY_BACKEND_URL=http://hockey-backend:8080

      # Frontend Configuration
      - NEXT_PUBLIC_API_URL=https://api.hockey.joseforge.cz  # UPDATED - Use correct env var name
      - NEXT_PUBLIC_ENV=production  # UPDATED - Use correct env var name
    depends_on:
      - hockey-backend
    restart: always

networks:
  traefik-net:
    external: true

