-- Core tables: country
-- Using STRICT for proper type enforcement and sqlx type inference

CREATE TABLE country (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  iso2Code TEXT,
  iocCode TEXT,
  iihf INTEGER NOT NULL DEFAULT 0,
  isHistorical INTEGER NOT NULL DEFAULT 0,
  years TEXT,
  enabled INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
) STRICT;

-- Country data - 213 countries including historical ones
INSERT INTO country (name, iihf, iso2Code, iocCode, isHistorical, years, enabled) VALUES
('Afghanistan', 0, 'AF','AFG', 0, NULL, 0),
('Albania', 0, 'AL','ALB', 0, NULL, 0),
('Algeria', 0, 'DZ','ALG', 0, NULL, 0),
('Andorra', 1, 'AD','AND', 0, NULL, 1),
('Angola', 0, 'AO','ANG', 0, NULL, 0),
('Antigua and Barbuda', 0, 'AG','ANT', 0, NULL, 0),
('Argentina', 1, 'AR','ARG', 0, NULL, 1),
('Armenia', 1, 'AM','ARM', 0, NULL, 1),
('Aruba', 0, 'AW','ARU', 0, NULL, 0),
('American Samoa', 0, 'AS','ASA', 0, NULL, 0),
('Australia', 1, 'AU','AUS', 0, NULL, 1),
('Austria', 1, 'AT','AUT', 0, NULL, 1),
('Azerbaijan', 1, 'AZ','AZE', 0, NULL, 1),
('Bahamas', 0, 'BS','BAH', 0, NULL, 0),
('Bangladesh', 0, 'BD','BAN', 0, NULL, 0),
('Barbados', 0, 'BB','BAR', 0, NULL, 0),
('Burundi', 0, 'BI','BDI', 0, NULL, 0),
('Belgium', 1, 'BE','BEL', 0, NULL, 1),
('Benin', 0, 'BJ','BEN', 0, NULL, 0),
('Bermuda', 0, 'BM','BER', 0, NULL, 0),
('Bhutan', 0, 'BT','BHU', 0, NULL, 0),
('Bosnia and Herzegovina', 1, 'BA','BIH', 0, NULL, 1),
('Belize', 0, 'BZ','BIZ', 0, NULL, 0),
('Belarus', 1, 'BY','BLR', 0, NULL, 1),
('Bolivia', 0, 'BO','BOL', 0, NULL, 0),
('Botswana', 0, 'BW','BOT', 0, NULL, 0),
('Brazil', 1, 'BR','BRA', 0, NULL, 1),
('Bahrain', 1, 'BH','BRN', 0, NULL, 1),
('Brunei', 0, 'BN','BRU', 0, NULL, 0),
('Bulgaria', 1, 'BG','BUL', 0, NULL, 1),
('Burkina Faso', 0, 'BF','BUR', 0, NULL, 0),
('Central African Republic', 0, 'CF','CAF', 0, NULL, 0),
('Cambodia', 0, 'KH','CAM', 0, NULL, 0),
('Canada', 1, 'CA','CAN', 0, NULL, 1),
('Cayman Islands', 0, 'KY','CAY', 0, NULL, 0),
('Republic of the Congo', 0, 'CG','CGO', 0, NULL, 0),
('Chad', 0, 'TD','CHA', 0, NULL, 0),
('Chile', 1, 'CL','CHI', 0, NULL, 1),
('China', 1, 'CN','CHN', 0, NULL, 1),
('Ivory Coast', 0, 'CI','CIV', 0, NULL, 0),
('Cameroon', 0, 'CM','CMR', 0, NULL, 0),
('Democratic Republic of the Congo', 0, 'CD','COD', 0, NULL, 0),
('Cook Islands', 0, 'CK','COK', 0, NULL, 0),
('Colombia', 1, 'CO','COL', 0, NULL, 1),
('Comoros', 0, 'KM','COM', 0, NULL, 0),
('Cape Verde', 0, 'CV','CPV', 0, NULL, 0),
('Costa Rica', 0, 'CR','CRC', 0, NULL, 0),
('Croatia', 1, 'HR','CRO', 0, NULL, 1),
('Cuba', 0, 'CU','CUB', 0, NULL, 0),
('Cyprus', 1, 'CY','CYP', 0, NULL, 1),
('Czechia', 1, 'CZ','CZE', 0, NULL, 1),
('Denmark', 1, 'DK','DEN', 0, NULL, 1),
('Djibouti', 0, 'DJ','DJI', 0, NULL, 0),
('Dominica', 0, 'DM','DMA', 0, NULL, 0),
('Dominican Republic', 0, 'DO','DOM', 0, NULL, 0),
('Ecuador', 0, 'EC','ECU', 0, NULL, 0),
('Egypt', 0, 'EG','EGY', 0, NULL, 0),
('Eritrea', 0, 'ER','ERI', 0, NULL, 0),
('El Salvador', 0, 'SV','ESA', 0, NULL, 0),
('Spain', 1, 'ES','ESP', 0, NULL, 1),
('Estonia', 1, 'EE','EST', 0, NULL, 1),
('Ethiopia', 0, 'ET','ETH', 0, NULL, 0),
('Unified Team', 1, NULL,'EUN', 1, '1992', 1),
('Fiji', 0, 'FJ','FIJ', 0, NULL, 0),
('Finland', 1, 'FI','FIN', 0, NULL, 1),
('France', 1, 'FR','FRA', 0, NULL, 1),
('West Germany', 1, NULL,'FRG', 1, '1956-1988', 1),
('Federated States of Micronesia', 0, 'FM','FSM', 0, NULL, 0),
('Gabon', 0, 'GA','GAB', 0, NULL, 0),
('The Gambia', 0, 'GM','GAM', 0, NULL, 0),
('Great Britain', 1, 'GB','GBR', 0, NULL, 1),
('Guinea-Bissau', 0, 'GW','GBS', 0, NULL, 0),
('East Germany', 1, NULL,'GDR', 1, '1956-1988', 1),
('Georgia', 1, 'GE','GEO', 0, NULL, 1),
('Equatorial Guinea', 0, 'GQ','GEQ', 0, NULL, 0),
('Germany', 1, 'DE','GER', 0, NULL, 1),
('Ghana', 0, 'GH','GHA', 0, NULL, 0),
('Greece', 1, 'GR','GRE', 0, NULL, 1),
('Grenada', 0, 'GD','GRN', 0, NULL, 0),
('Guatemala', 0, 'GT','GUA', 0, NULL, 0),
('Guinea', 0, 'GN','GUI', 0, NULL, 0),
('Guam', 0, 'GU','GUM', 0, NULL, 0),
('Guyana', 0, 'GY','GUY', 0, NULL, 0),
('Haiti', 0, 'HT','HAI', 0, NULL, 0),
('Hong Kong', 1, 'HK','HKG', 0, NULL, 1),
('Honduras', 0, 'HN','HON', 0, NULL, 0),
('Hungary', 1, 'HU','HUN', 0, NULL, 1),
('Iceland', 1, 'IS','ISL', 0, NULL, 1),
('India', 1, 'IN','IND', 0, NULL, 1),
('Indonesia', 1, 'ID','INA', 0, NULL, 1),
('Iran', 0, 'IR','IRI', 0, NULL, 0),
('Iraq', 1, 'IQ','IRQ', 0, NULL, 1),
('Ireland', 1, 'IE','IRL', 0, NULL, 1),
('Israel', 1, 'IL','ISR', 0, NULL, 1),
('Italy', 1, 'IT','ITA', 0, NULL, 1),
('Jamaica', 1, 'JM','JAM', 0, NULL, 1),
('Japan', 1, 'JP','JPN', 0, NULL, 1),
('Jordan', 0, 'JO','JOR', 0, NULL, 0),
('Kazakhstan', 1, 'KZ','KAZ', 0, NULL, 1),
('Kenya', 1, 'KE','KEN', 0, NULL, 1),
('Kyrgyzstan', 1, 'KG','KGZ', 0, NULL, 1),
('Kiribati', 0, 'KI','KIR', 0, NULL, 0),
('South Korea', 1, 'KR','KOR', 0, NULL, 1),
('Kosovo', 1, 'XK','KOS', 0, NULL, 1),
('Kuwait', 1, 'KW','KUW', 0, NULL, 1),
('Laos', 0, 'LA','LAO', 0, NULL, 0),
('Latvia', 1, 'LV','LAT', 0, NULL, 1),
('Lebanon', 1, 'LB','LIB', 0, NULL, 1),
('Liberia', 0, 'LR','LBR', 0, NULL, 0),
('Libya', 0, 'LY','LBA', 0, NULL, 0),
('Saint Lucia', 0, 'LC','LCA', 0, NULL, 0),
('Lesotho', 0, 'LS','LES', 0, NULL, 0),
('Lithuania', 1, 'LT','LTU', 0, NULL, 1),
('Liechtenstein', 1, 'LI','LIE', 0, NULL, 1),
('Luxembourg', 1, 'LU','LUX', 0, NULL, 1),
('Madagascar', 1, 'MG','MAD', 0, NULL, 1),
('Malaysia', 1, 'MY','MAS', 0, NULL, 1),
('Malawi', 0, 'MW','MAW', 0, NULL, 0),
('Maldives', 0, 'MV','MDV', 0, NULL, 0),
('Mexico', 1, 'MX','MEX', 0, NULL, 1),
('Mongolia', 1, 'MN','MGL', 0, NULL, 1),
('Moldova', 1, 'MD','MDA', 0, NULL, 1),
('Monaco', 0, 'MC','MON', 0, NULL, 0),
('Morocco', 1, 'MA','MAR', 0, NULL, 1),
('Mozambique', 0, 'MZ','MOZ', 0, NULL, 0),
('Mauritius', 0, 'MU','MRI', 0, NULL, 0),
('Mauritania', 0, 'MR','MTN', 0, NULL, 0),
('Myanmar', 0, 'MM','MYA', 0, NULL, 0),
('Namibia', 1, 'NA','NAM', 0, NULL, 1),
('Nauru', 0, 'NR','NRU', 0, NULL, 0),
('Nepal', 0, 'NP','NEP', 0, NULL, 0),
('Netherlands', 1, 'NL','NED', 0, NULL, 1),
('New Zealand', 1, 'NZ','NZL', 0, NULL, 1),
('Nicaragua', 0, 'NI','NCA', 0, NULL, 0),
('Niger', 0, 'NE','NIG', 0, NULL, 0),
('Nigeria', 1, 'NG','NGR', 0, NULL, 1),
('Norway', 1, 'NO','NOR', 0, NULL, 1),
('North Korea', 1, 'KP','PRK', 0, NULL, 1),
('North Macedonia', 1, 'MK','MKD', 0, NULL, 1),
('Oman', 1, 'OM','OMA', 0, NULL, 1),
('Pakistan', 1, 'PK','PAK', 0, NULL, 1),
('Panama', 0, 'PA','PAN', 0, NULL, 0),
('Paraguay', 0, 'PY','PAR', 0, NULL, 0),
('Peru', 0, 'PE','PER', 0, NULL, 0),
('Philippines', 1, 'PH','PHI', 0, NULL, 1),
('Palau', 0, 'PW','PLW', 0, NULL, 0),
('Papua New Guinea', 0, 'PG','PNG', 0, NULL, 0),
('Poland', 1, 'PL','POL', 0, NULL, 1),
('Portugal', 1, 'PT','POR', 0, NULL, 1),
('Puerto Rico', 1, 'PR','PUR', 0, NULL, 1),
('Qatar', 1, 'QA','QAT', 0, NULL, 1),
('Romania', 1, 'RO','ROU', 0, NULL, 1),
('Russia', 1, 'RU','RUS', 0, NULL, 1),
('Rwanda', 0, 'RW','RWA', 0, NULL, 0),
('Saudi Arabia', 0, 'SA','KSA', 0, NULL, 0),
('Senegal', 0, 'SN','SEN', 0, NULL, 0),
('Singapore', 1, 'SG','SGP', 0, NULL, 1),
('Solomon Islands', 0, 'SB','SOL', 0, NULL, 0),
('Somalia', 0, 'SO','SOM', 0, NULL, 0),
('South Africa', 1, 'ZA','RSA', 0, NULL, 1),
('South Sudan', 0, 'SS','SSD', 0, NULL, 0),
('Zimbabwe', 0, 'ZW','ZIM', 0, NULL, 0),
('Serbia', 1, 'RS','SRB', 0, NULL, 1),
('Soviet Union', 1, NULL,'URS', 1, '1952-1992', 1),
('Sri Lanka', 0, 'LK','SRI', 0, NULL, 0),
('Sudan', 0, 'SD','SUD', 0, NULL, 0),
('Suriname', 0, 'SR','SUR', 0, NULL, 0),
('Sweden', 1, 'SE','SWE', 0, NULL, 1),
('Switzerland', 1, 'CH','SUI', 0, NULL, 1),
('Syria', 0, 'SY','SYR', 0, NULL, 0),
('Tajikistan', 0, 'TJ','TJK', 0, NULL, 0),
('Thailand', 1, 'TH','THA', 0, NULL, 1),
('North Yemen', 0, NULL,'YAR', 1, '1965-1990', 1),
('The Bahamas', 0, 'BS','BAH', 0, NULL, 0),
('Togo', 0, 'TG','TOG', 0, NULL, 0),
('Tonga', 0, 'TO','TGA', 0, NULL, 0),
('Trinidad and Tobago', 0, 'TT','TTO', 0, NULL, 0),
('Tunisia', 0, 'TN','TUN', 0, NULL, 0),
('Turkey', 1, 'TR','TUR', 0, NULL, 1),
('Turkmenistan', 1, 'TM','TKM', 0, NULL, 1),
('Tuvalu', 0, 'TV','TUV', 0, NULL, 0),
('Chinese Taipei', 1, 'TW','TPE', 0, NULL, 1),
('Tanzania', 0, 'TZ','TAN', 0, NULL, 0),
('Uganda', 0, 'UG','UGA', 0, NULL, 0),
('Ukraine', 1, 'UA','UKR', 0, NULL, 1),
('Uruguay', 0, 'UY','URU', 0, NULL, 0),
('United States', 1, 'US','USA', 0, NULL, 1),
('Uzbekistan', 1, 'UZ','UZB', 0, NULL, 1),
('Saint Vincent and the Grenadines', 0, 'VC','VIN', 0, NULL, 0),
('Venezuela', 0, 'VE','VEN', 0, NULL, 0),
('British Virgin Islands', 0, 'VG','IVB', 0, NULL, 0),
('United States Virgin Islands', 0, 'VI','ISV', 0, NULL, 0),
('Vietnam', 0, 'VN','VIE', 0, NULL, 0),
('Vanuatu', 0, 'VU','VAN', 0, NULL, 0),
('Samoa', 0, 'WS','SAM', 0, NULL, 0),
('Yemen', 0, 'YE','YEM', 0, NULL, 0),
('Yugoslavia', 1, NULL,'YUG', 1, '1920-2003', 1),
('Zambia', 0, 'ZM','ZAM', 0, NULL, 0);
