DROP TABLE IF EXISTS country;

CREATE TABLE country (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  iihf BOOLEAN DEFAULT FALSE,
  iocCode TEXT,
  iso2Code TEXT,
  isHistorical BOOLEAN DEFAULT FALSE,
  years TEXT,
  enabled BOOLEAN DEFAULT FALSE
);

-- SQL INSERT statements for countries table
-- Note: Using 'code' as the primary key instead of auto-increment id since that's what you'll reference

INSERT INTO country (name, iihf, iso2Code, iocCode, isHistorical, years, enabled) VALUES
('Afghanistan', FALSE, 'AF','AFG', FALSE, NULL, FALSE),
('Albania', FALSE, 'AL','ALB', FALSE, NULL, FALSE),
('Algeria', FALSE, 'DZ','ALG', FALSE, NULL, FALSE),
('Andorra', TRUE, 'AD','AND', FALSE, NULL, FALSE),
('Angola', FALSE, 'AO','ANG', FALSE, NULL, FALSE),
('Antigua and Barbuda', FALSE, 'AG','ANT', FALSE, NULL, FALSE),
('Argentina', TRUE, 'AR','ARG', FALSE, NULL, FALSE),
('Armenia', TRUE, 'AM','ARM', FALSE, NULL, FALSE),
('Aruba', FALSE, 'AW','ARU', FALSE, NULL, FALSE),
('American Samoa', FALSE, 'AS','ASA', FALSE, NULL, FALSE),
('Australia', TRUE, 'AU','AUS', FALSE, NULL, FALSE),
('Austria', TRUE, 'AT','AUT', FALSE, NULL, FALSE),
('Azerbaijan', TRUE, 'AZ','AZE', FALSE, NULL, FALSE),
('Bahamas', FALSE, 'BS','BAH', FALSE, NULL, FALSE),
('Bangladesh', FALSE, 'BD','BAN', FALSE, NULL, FALSE),
('Barbados', FALSE, 'BB','BAR', FALSE, NULL, FALSE),
('Burundi', FALSE, 'BI','BDI', FALSE, NULL, FALSE),
('Belgium', TRUE, 'BE','BEL', FALSE, NULL, FALSE),
('Benin', FALSE, 'BJ','BEN', FALSE, NULL, FALSE),
('Bermuda', FALSE, 'BM','BER', FALSE, NULL, FALSE),
('Bhutan', FALSE, 'BT','BHU', FALSE, NULL, FALSE),
('Bosnia and Herzegovina', TRUE, 'BA','BIH', FALSE, NULL, FALSE),
('Belize', FALSE, 'BZ','BIZ', FALSE, NULL, FALSE),
('Belarus', TRUE, 'BY','BLR', FALSE, NULL, FALSE),
('Bolivia', FALSE, 'BO','BOL', FALSE, NULL, FALSE),
('Botswana', FALSE, 'BW','BOT', FALSE, NULL, FALSE),
('Brazil', TRUE, 'BR','BRA', FALSE, NULL, FALSE),
('Bahrain', TRUE, 'BH','BRN', FALSE, NULL, FALSE),
('Brunei', FALSE, 'BN','BRU', FALSE, NULL, FALSE),
('Bulgaria', TRUE, 'BG','BUL', FALSE, NULL, FALSE),
('Burkina Faso', FALSE, 'BF','BUR', FALSE, NULL, FALSE),
('Central African Republic', FALSE, 'CF','CAF', FALSE, NULL, FALSE),
('Cambodia', FALSE, 'KH','CAM', FALSE, NULL, FALSE),
('Canada', TRUE, 'CA','CAN', FALSE, NULL, FALSE),
('Cayman Islands', FALSE, 'KY','CAY', FALSE, NULL, FALSE),
('Republic of the Congo', FALSE, 'CG','CGO', FALSE, NULL, FALSE),
('Chad', FALSE, 'TD','CHA', FALSE, NULL, FALSE),
('Chile', TRUE, 'CL','CHI', FALSE, NULL, FALSE),
('China', TRUE, 'CN','CHN', FALSE, NULL, FALSE),
('Ivory Coast', FALSE, 'CI','CIV', FALSE, NULL, FALSE),
('Cameroon', FALSE, 'CM','CMR', FALSE, NULL, FALSE),
('Democratic Republic of the Congo', FALSE, 'CD','COD', FALSE, NULL, FALSE),
('Cook Islands', FALSE, 'CK','COK', FALSE, NULL, FALSE),
('Colombia', TRUE, 'CO','COL', FALSE, NULL, FALSE),
('Comoros', FALSE, 'KM','COM', FALSE, NULL, FALSE),
('Cape Verde', FALSE, 'CV','CPV', FALSE, NULL, FALSE),
('Costa Rica', FALSE, 'CR','CRC', FALSE, NULL, FALSE),
('Croatia', TRUE, 'HR','CRO', FALSE, NULL, FALSE),
('Cuba', FALSE, 'CU','CUB', FALSE, NULL, FALSE),
('Cyprus', TRUE, 'CY','CYP', FALSE, NULL, FALSE),
('Czechia', TRUE, 'CZ','CZE', FALSE, NULL, FALSE),
('Denmark', TRUE, 'DK','DEN', FALSE, NULL, FALSE),
('Djibouti', FALSE, 'DJ','DJI', FALSE, NULL, FALSE),
('Dominica', FALSE, 'DM','DMA', FALSE, NULL, FALSE),
('Dominican Republic', FALSE, 'DO','DOM', FALSE, NULL, FALSE),
('Ecuador', FALSE, 'EC','ECU', FALSE, NULL, FALSE),
('Egypt', FALSE, 'EG','EGY', FALSE, NULL, FALSE),
('Eritrea', FALSE, 'ER','ERI', FALSE, NULL, FALSE),
('El Salvador', FALSE, 'SV','ESA', FALSE, NULL, FALSE),
('Spain', TRUE, 'ES','ESP', FALSE, NULL, FALSE),
('Estonia', TRUE, 'EE','EST', FALSE, NULL, FALSE),
('Ethiopia', FALSE, 'ET','ETH', FALSE, NULL, FALSE),
('Unified Team', TRUE, NULL,'EUN', TRUE, '1992', FALSE),
('Fiji', FALSE, 'FJ','FIJ', FALSE, NULL, FALSE),
('Finland', TRUE, 'FI','FIN', FALSE, NULL, FALSE),
('France', TRUE, 'FR','FRA', FALSE, NULL, FALSE),
('West Germany', TRUE, NULL,'FRG', TRUE, '1956-1988', FALSE),
('Federated States of Micronesia', FALSE, 'FM','FSM', FALSE, NULL, FALSE),
('Gabon', FALSE, 'GA','GAB', FALSE, NULL, FALSE),
('The Gambia', FALSE, 'GM','GAM', FALSE, NULL, FALSE),
('Great Britain', TRUE, 'GB','GBR', FALSE, NULL, FALSE),
('Guinea-Bissau', FALSE, 'GW','GBS', FALSE, NULL, FALSE),
('East Germany', TRUE, NULL,'GDR', TRUE, '1956-1988', FALSE),
('Georgia', TRUE, 'GE','GEO', FALSE, NULL, FALSE),
('Equatorial Guinea', FALSE, 'GQ','GEQ', FALSE, NULL, FALSE),
('Germany', TRUE, 'DE','GER', FALSE, NULL, FALSE),
('Ghana', FALSE, 'GH','GHA', FALSE, NULL, FALSE),
('Greece', TRUE, 'GR','GRE', FALSE, NULL, FALSE),
('Grenada', FALSE, 'GD','GRN', FALSE, NULL, FALSE),
('Guatemala', FALSE, 'GT','GUA', FALSE, NULL, FALSE),
('Guinea', FALSE, 'GN','GUI', FALSE, NULL, FALSE),
('Guam', FALSE, 'GU','GUM', FALSE, NULL, FALSE),
('Guyana', FALSE, 'GY','GUY', FALSE, NULL, FALSE),
('Haiti', FALSE, 'HT','HAI', FALSE, NULL, FALSE),
('Hong Kong', TRUE, 'HK','HKG', FALSE, NULL, FALSE),
('Honduras', FALSE, 'HN','HON', FALSE, NULL, FALSE),
('Hungary', TRUE, 'HU','HUN', FALSE, NULL, FALSE),
('Indonesia', TRUE, 'ID','INA', FALSE, NULL, FALSE),
('India', TRUE, 'IN','IND', FALSE, NULL, FALSE),
('Iran', FALSE, 'IR','IRI', FALSE, NULL, FALSE),
('Ireland', TRUE, 'IE','IRL', FALSE, NULL, FALSE),
('Iraq', TRUE, 'IQ','IRQ', FALSE, NULL, FALSE),
('Iceland', TRUE, 'IS','ISL', FALSE, NULL, FALSE),
('Israel', TRUE, 'IL','ISR', FALSE, NULL, FALSE),
('Virgin Islands', FALSE, 'VI','ISV', FALSE, NULL, FALSE),
('Italy', TRUE, 'IT','ITA', FALSE, NULL, FALSE),
('British Virgin Islands', FALSE, 'VG','IVB', FALSE, NULL, FALSE),
('Jamaica', FALSE, 'JM','JAM', FALSE, NULL, FALSE),
('Jordan', FALSE, 'JO','JOR', FALSE, NULL, FALSE),
('Japan', TRUE, 'JP','JPN', FALSE, NULL, FALSE),
('Kazakhstan', TRUE, 'KZ','KAZ', FALSE, NULL, FALSE),
('Kenya', TRUE, 'KE','KEN', FALSE, NULL, FALSE),
('Kyrgyzstan', TRUE, 'KG','KGZ', FALSE, NULL, FALSE),
('Kiribati', FALSE, 'KI','KIR', FALSE, NULL, FALSE),
('South Korea', TRUE, 'KR','KOR', FALSE, NULL, FALSE),
('Kosovo', FALSE, 'XK','KOS', FALSE, NULL, FALSE),
('Saudi Arabia', FALSE, 'SA','KSA', FALSE, NULL, FALSE),
('Kuwait', TRUE, 'KW','KUW', FALSE, NULL, FALSE),
('Laos', FALSE, 'LA','LAO', FALSE, NULL, FALSE),
('Latvia', TRUE, 'LV','LAT', FALSE, NULL, FALSE),
('Libya', FALSE, 'LY','LBA', FALSE, NULL, FALSE),
('Lebanon', TRUE, 'LB','LBN', FALSE, NULL, FALSE),
('Liberia', FALSE, 'LR','LBR', FALSE, NULL, FALSE),
('Saint Lucia', FALSE, 'LC','LCA', FALSE, NULL, FALSE),
('Lesotho', FALSE, 'LS','LES', FALSE, NULL, FALSE),
('Liechtenstein', TRUE, 'LI','LIE', FALSE, NULL, FALSE),
('Lithuania', TRUE, 'LT','LTU', FALSE, NULL, FALSE),
('Luxembourg', TRUE, 'LU','LUX', FALSE, NULL, FALSE),
('Madagascar', FALSE, 'MG','MAD', FALSE, NULL, FALSE),
('Morocco', TRUE, 'MA','MAR', FALSE, NULL, FALSE),
('Malaysia', TRUE, 'MY','MAS', FALSE, NULL, FALSE),
('Malawi', FALSE, 'MW','MAW', FALSE, NULL, FALSE),
('Moldova', TRUE, 'MD','MDA', FALSE, NULL, FALSE),
('Maldives', FALSE, 'MV','MDV', FALSE, NULL, FALSE),
('Mexico', TRUE, 'MX','MEX', FALSE, NULL, FALSE),
('Mongolia', TRUE, 'MN','MGL', FALSE, NULL, FALSE),
('Marshall Islands', FALSE, 'MH','MHL', FALSE, NULL, FALSE),
('North Macedonia', TRUE, 'MK','MKD', FALSE, NULL, FALSE),
('Mali', FALSE, 'ML','MLI', FALSE, NULL, FALSE),
('Malta', TRUE, 'MT','MLT', FALSE, NULL, FALSE),
('Montenegro', TRUE, 'ME','MNE', FALSE, NULL, FALSE),
('Monaco', TRUE, 'MC','MON', FALSE, NULL, FALSE),
('Mozambique', FALSE, 'MZ','MOZ', FALSE, NULL, FALSE),
('Mauritius', FALSE, 'MU','MRI', FALSE, NULL, FALSE),
('Mauritania', FALSE, 'MR','MTN', FALSE, NULL, FALSE),
('Myanmar', FALSE, 'MM','MYA', FALSE, NULL, FALSE),
('Namibia', TRUE, 'NA','NAM', FALSE, NULL, FALSE),
('Nicaragua', FALSE, 'NI','NCA', FALSE, NULL, FALSE),
('Netherlands', TRUE, 'NL','NED', FALSE, NULL, FALSE),
('Nepal', TRUE, 'NP','NEP', FALSE, NULL, FALSE),
('Nigeria', FALSE, 'NG','NGR', FALSE, NULL, FALSE),
('Niger', FALSE, 'NE','NIG', FALSE, NULL, FALSE),
('Norway', TRUE, 'NO','NOR', FALSE, NULL, FALSE),
('Nauru', FALSE, 'NR','NRU', FALSE, NULL, FALSE),
('New Zealand', TRUE, 'NZ','NZL', FALSE, NULL, FALSE),
('Oman', FALSE, 'OM','OMA', FALSE, NULL, FALSE),
('Pakistan', FALSE, 'PK','PAK', FALSE, NULL, FALSE),
('Panama', FALSE, 'PA','PAN', FALSE, NULL, FALSE),
('Paraguay', FALSE, 'PY','PAR', FALSE, NULL, FALSE),
('Peru', FALSE, 'PE','PER', FALSE, NULL, FALSE),
('Philippines', TRUE, 'PH','PHI', FALSE, NULL, FALSE),
('Palestine', FALSE, 'PS','PLE', FALSE, NULL, FALSE),
('Palau', FALSE, 'PW','PLW', FALSE, NULL, FALSE),
('Papua New Guinea', FALSE, 'PG','PNG', FALSE, NULL, FALSE),
('Poland', TRUE, 'PL','POL', FALSE, NULL, FALSE),
('Portugal', TRUE, 'PT','POR', FALSE, NULL, FALSE),
('North Korea', TRUE, 'KP','PRK', FALSE, NULL, FALSE),
('Puerto Rico', FALSE, 'PR','PUR', FALSE, NULL, FALSE),
('Qatar', FALSE, 'QA','QAT', FALSE, NULL, FALSE),
('Romania', TRUE, 'RO','ROU', FALSE, NULL, FALSE),
('South Africa', TRUE, 'ZA','RSA', FALSE, NULL, FALSE),
('Russia', TRUE, 'RU','RUS', FALSE, NULL, FALSE),
('Rwanda', FALSE, 'RW','RWA', FALSE, NULL, FALSE),
('Samoa', FALSE, 'WS','SAM', FALSE, NULL, FALSE),
('Serbia and Montenegro', TRUE, NULL,'SCG', TRUE, '2003-2006', FALSE),
('Senegal', FALSE, 'SN','SEN', FALSE, NULL, FALSE),
('Seychelles', FALSE, 'SC','SEY', FALSE, NULL, FALSE),
('Singapore', TRUE, 'SG','SGP', FALSE, NULL, FALSE),
('Saint Kitts and Nevis', FALSE, 'KN','SKN', FALSE, NULL, FALSE),
('Sierra Leone', FALSE, 'SL','SLE', FALSE, NULL, FALSE),
('Slovenia', TRUE, 'SI','SLO', FALSE, NULL, FALSE),
('San Marino', FALSE, 'SM','SMR', FALSE, NULL, FALSE),
('Solomon Islands', FALSE, 'SB','SOL', FALSE, NULL, FALSE),
('Somalia', FALSE, 'SO','SOM', FALSE, NULL, FALSE),
('Serbia', TRUE, 'RS','SRB', FALSE, NULL, FALSE),
('Sri Lanka', FALSE, 'LK','SRI', FALSE, NULL, FALSE),
('South Sudan', FALSE, 'SS','SSD', FALSE, NULL, FALSE),
('São Tomé and Príncipe', FALSE, 'ST','STP', FALSE, NULL, FALSE),
('Sudan', FALSE, 'SD','SUD', FALSE, NULL, FALSE),
('Switzerland', TRUE, 'CH','SUI', FALSE, NULL, FALSE),
('Suriname', FALSE, 'SR','SUR', FALSE, NULL, FALSE),
('Slovakia', TRUE, 'SK','SVK', FALSE, NULL, FALSE),
('Sweden', TRUE, 'SE','SWE', FALSE, NULL, FALSE),
('Eswatini', FALSE, 'SZ','SWZ', FALSE, NULL, FALSE),
('Syria', FALSE, 'SY','SYR', FALSE, NULL, FALSE),
('Tanzania', FALSE, 'TZ','TAN', FALSE, NULL, FALSE),
('Czechoslovakia', TRUE, NULL, 'TCH',TRUE, '1920-1992', FALSE),
('Tonga', FALSE, 'TO','TGA', FALSE, NULL, FALSE),
('Thailand', TRUE, 'TH','THA', FALSE, NULL, FALSE),
('Tajikistan', FALSE, 'TJ','TJK', FALSE, NULL, FALSE),
('Turkmenistan', TRUE, 'TM','TKM', FALSE, NULL, FALSE),
('Timor-Leste', FALSE, 'TL','TLS', FALSE, NULL, FALSE),
('Togo', FALSE, 'TG','TOG', FALSE, NULL, FALSE),
('Chinese Taipei', TRUE, 'TW','TPE', FALSE, NULL, FALSE),
('Trinidad and Tobago', FALSE, 'TT','TTO', FALSE, NULL, FALSE),
('Tunisia', FALSE, 'TN','TUN', FALSE, NULL, FALSE),
('Turkey', TRUE, 'TR','TUR', FALSE, NULL, FALSE),
('Tuvalu', FALSE, 'TV','TUV', FALSE, NULL, FALSE),
('United Arab Emirates', TRUE, 'AE','UAE', FALSE, NULL, FALSE),
('Uganda', FALSE, 'UG','UGA', FALSE, NULL, FALSE),
('Ukraine', TRUE, 'UA','UKR', FALSE, NULL, FALSE),
('Soviet Union', TRUE, NULL, 'URS',TRUE, '1952-1991', FALSE),
('Uruguay', FALSE, 'UY','URU', FALSE, NULL, FALSE),
('United States', TRUE, 'US','USA', FALSE, NULL, FALSE),
('Uzbekistan', FALSE, 'UZ','UZB', FALSE, NULL, FALSE),
('Vanuatu', FALSE, 'VU','VAN', FALSE, NULL, FALSE),
('Venezuela', FALSE, 'VE','VEN', FALSE, NULL, FALSE),
('Vietnam', FALSE, 'VN','VIE', FALSE, NULL, FALSE),
('Saint Vincent and the Grenadines', FALSE, 'VC','VIN', FALSE, NULL, FALSE),
('Yemen', FALSE, 'YE','YEM', FALSE, NULL, FALSE),
('Yugoslavia', TRUE, NULL, 'YUG',TRUE, '1920-1992', FALSE),
('Zambia', FALSE, 'ZM','ZAM', FALSE, NULL, FALSE),
('Zimbabwe', FALSE, 'ZW','ZIM', FALSE, NULL, FALSE);

UPDATE country SET enabled = true WHERE iihf = true or "isHistorical" = true;